Repository tokai-student-rocket-project/tokai-student-rocket-project.github.io, pull requests merged in 2022-08, with the labels that each got.

#36 環境構築のマニュアルを暫定的に作成しました
  README.md
  docs/Setup.md
  package-lock.json
Labels: ドキュメント, 新規追加

#37 Node.jsのインストール手順をマニュアルに追
  docs/Setup.md
Labels: ドキュメント, 新規追加

#38 不要な記述を削除
  docs/Setup.md
Labels: ドキュメント, 修正

#39 READMEにライセンスを追加
  README.md
Labels: ドキュメント, 新規追加

#45 マニュアルにフィードバックを反映
  docs/Setup.md
Labels: ドキュメント, 修正

#50 "開発"ドキュメントを追加
  README.md
  docs/Development.md
Labels: ドキュメント, 新規追加

#63 feature/#46-refactor-top-page
  package-lock.json
  package.json
  src/components/pages/Top/Top.tsx
Labels: 改善
